### ISSUE TITLE
Patches limited?

### ISSUE THREAD

**Issue by BastiBlue** [TheZoc/ZPatcher#15]
basepatch works, first update works too, second and more updates are not working.
single patch not working, only together with first update
after the first update always the message "up-to-date".
zpatcher.zversion only contains blank characters?

is there a solution to delete the temporal downloads in the directory updates?
The downloaded server-side xml should also be deleted

**Comment by TheZoc** [comment]
Hello @BastiBlue,

What compiler did you use to compile ZPacher? There's a report that outdated versions of VS2017 (and/or outdated versions of their VC++ Redistributable package) might cause issues with patch unpacking. Link to the report: #13 

If you're on latest version, you might have hit a bug.

`zpatcher.zversion` needs to be opened with a Hex Editor so you can see its contents. Version info is not stored in plain text :)

To delete downloaded files it's quite easy, just need a minor modification to the code. It wasn't being deleted to aid in testing. I can change that later for you! (I might just need a couple days since I'm with my hands full ATM)

If you're still with problems, would you mind if I take a peek in your patch files? It might help me to understand and solve this issue.

Since GitHub social features are limited, you can reach me in twitter ( @ zoc ). If you prefer another way, please, let me know!

Looking forward to your reply!

**Comment by TheZoc** [comment]
Closed due to inactivity.
