### ISSUE TITLE
wxprec.h 

### ISSUE THREAD

**Issue by Reck1501** [TheZoc/ZPatcher#2]
I get 
"4>c:\users\reck\desktop\zpatcher-master\visualcreatepatch\stdafx.h(9): fatal error C1083: Cannot open include file: 'wx/wxprec.h': No such file or directory"
whenever I attempt to compile.

I'm trying to compile with VS2015

**Comment by TheZoc** [comment]
Hello @Reck1501,

Yesterday I pushed a commit with a proof-of-concept Visual Create Patch tool. It's the same tool as CreatePatch, but displays a simple window instead of a console-based output.
You can use the zPatcher toolset without it, for now.

I'll add instructions to ReadMe soon, but if you're really eager to compile it, you can download wxWidgets (there are pre-compiled binaries [here](https://github.com/wxWidgets/wxWidgets/releases)), add them to `libs/wxWidgets/include` and `libs/wxWidgets/lib`.
Please note that the precompiled wxwidgets will come with a lib name for it's directory as something like `vc140_x64_dll`, you will need to rename it to `vc_x64_dll`.

If you compile it, tell me how it went, please :)

**Comment by Reck1501** [comment]
I did manage to compile it after a while, although I had to build the .lib files of wxWidget myself.

Oh, and how does the visual creator work? It is still requesting a commandline input when I attempt opening it

**Comment by TheZoc** [comment]
Currently it works pretty much the same as the command line one, requiring command line input.
Adding a directory open dialog is definitely possible using a couple `wxDirDialog` and a `wxFileDialog`.

I probably won't be able to do it for a while, but feel free to submit a pull request in case you end up coding it in :grinning:

**Comment by Reck1501** [comment]
Will do :)
